-- liquibase formatted sql


DROP TABLE IF EXISTS rule_table CASCADE;
CREATE TABLE rule_table(
    id INTEGER GENERATED BY DEFAULT PRIMARY KEY,
    recommendation_id INTEGER FOREIGN KEY REFERENCES recommendation_table (id);
    query TEXT NOT NULL,
    arguments TEXT NOT NULL,
    negate BOOLEAN NOT NULL
);