--liquibase formatted sql
--changeset sergei.shishkin:create_statistic


CREATE TABLE if NOT EXISTS statistic (
    id BIGINT generated by default as identity primary key,
    recommendation_id BIGINT not null,
    counter INTEGER
);