-- liquibase formatted sql


DROP TABLE IF EXISTS recommendation_table CASCADE;
CREATE TABLE recommendation_table(
    id INTEGER GENERATED BY DEFAULT PRIMARY KEY
    name TEXT NOT NULL,
    product_id UUID GENERATED BY DEFAULT,
    description TEXT NOT NULL
);